# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'starter.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 895)
        MainWindow.setMinimumSize(QtCore.QSize(830, 895))
        MainWindow.setMaximumSize(QtCore.QSize(830, 895))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab1)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 781, 761))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 19, 371, 731))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_14 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_14.setObjectName("groupBox_14")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_14)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(49, 10, 311, 22))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PlayerMaleCombo1 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.PlayerMaleCombo1.setObjectName("PlayerMaleCombo1")
        self.horizontalLayout_2.addWidget(self.PlayerMaleCombo1)
        self.PlayerMaleCheck1 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.PlayerMaleCheck1.setObjectName("PlayerMaleCheck1")
        self.horizontalLayout_2.addWidget(self.PlayerMaleCheck1)
        self.verticalLayout_4.addWidget(self.groupBox_14)
        self.groupBox_15 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_15.setObjectName("groupBox_15")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_15)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.PlayerMaleCombo2 = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.PlayerMaleCombo2.setObjectName("PlayerMaleCombo2")
        self.horizontalLayout_5.addWidget(self.PlayerMaleCombo2)
        self.PlayerMaleCheck2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.PlayerMaleCheck2.setObjectName("PlayerMaleCheck2")
        self.horizontalLayout_5.addWidget(self.PlayerMaleCheck2)
        self.verticalLayout_4.addWidget(self.groupBox_15)
        self.groupBox_13 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_13.setObjectName("groupBox_13")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_13)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.PlayerMaleCombo3 = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        self.PlayerMaleCombo3.setObjectName("PlayerMaleCombo3")
        self.horizontalLayout_6.addWidget(self.PlayerMaleCombo3)
        self.PlayerMaleCheck3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        self.PlayerMaleCheck3.setObjectName("PlayerMaleCheck3")
        self.horizontalLayout_6.addWidget(self.PlayerMaleCheck3)
        self.verticalLayout_4.addWidget(self.groupBox_13)
        self.groupBox_12 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_12)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.PlayerMaleCombo4 = QtWidgets.QComboBox(self.horizontalLayoutWidget_5)
        self.PlayerMaleCombo4.setObjectName("PlayerMaleCombo4")
        self.horizontalLayout_7.addWidget(self.PlayerMaleCombo4)
        self.PlayerMaleCheck4 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        self.PlayerMaleCheck4.setObjectName("PlayerMaleCheck4")
        self.horizontalLayout_7.addWidget(self.PlayerMaleCheck4)
        self.verticalLayout_4.addWidget(self.groupBox_12)
        self.groupBox_11 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_11)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.PlayerMaleCombo5 = QtWidgets.QComboBox(self.horizontalLayoutWidget_6)
        self.PlayerMaleCombo5.setObjectName("PlayerMaleCombo5")
        self.horizontalLayout_8.addWidget(self.PlayerMaleCombo5)
        self.PlayerMaleCheck5 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_6)
        self.PlayerMaleCheck5.setObjectName("PlayerMaleCheck5")
        self.horizontalLayout_8.addWidget(self.PlayerMaleCheck5)
        self.verticalLayout_4.addWidget(self.groupBox_11)
        self.groupBox_16 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_16.setObjectName("groupBox_16")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_16)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.PlayerMaleCombo6 = QtWidgets.QComboBox(self.horizontalLayoutWidget_7)
        self.PlayerMaleCombo6.setObjectName("PlayerMaleCombo6")
        self.horizontalLayout_9.addWidget(self.PlayerMaleCombo6)
        self.PlayerMaleCheck6 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_7)
        self.PlayerMaleCheck6.setObjectName("PlayerMaleCheck6")
        self.horizontalLayout_9.addWidget(self.PlayerMaleCheck6)
        self.verticalLayout_4.addWidget(self.groupBox_16)
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.PlayerMaleCombo7 = QtWidgets.QComboBox(self.horizontalLayoutWidget_8)
        self.PlayerMaleCombo7.setObjectName("PlayerMaleCombo7")
        self.horizontalLayout_10.addWidget(self.PlayerMaleCombo7)
        self.PlayerMaleCheck7 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_8)
        self.PlayerMaleCheck7.setObjectName("PlayerMaleCheck7")
        self.horizontalLayout_10.addWidget(self.PlayerMaleCheck7)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.PlayerMaleCombo8 = QtWidgets.QComboBox(self.horizontalLayoutWidget_9)
        self.PlayerMaleCombo8.setObjectName("PlayerMaleCombo8")
        self.horizontalLayout_11.addWidget(self.PlayerMaleCombo8)
        self.PlayerMaleCheck8 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_9)
        self.PlayerMaleCheck8.setObjectName("PlayerMaleCheck8")
        self.horizontalLayout_11.addWidget(self.PlayerMaleCheck8)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_17 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_17.setObjectName("groupBox_17")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_17)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.PlayerMaleCombo9 = QtWidgets.QComboBox(self.horizontalLayoutWidget_10)
        self.PlayerMaleCombo9.setObjectName("PlayerMaleCombo9")
        self.horizontalLayout_12.addWidget(self.PlayerMaleCombo9)
        self.PlayerMaleCheck9 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_10)
        self.PlayerMaleCheck9.setObjectName("PlayerMaleCheck9")
        self.horizontalLayout_12.addWidget(self.PlayerMaleCheck9)
        self.verticalLayout_4.addWidget(self.groupBox_17)
        self.groupBox_5 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.groupBox_5)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.PlayerMaleCombo10 = QtWidgets.QComboBox(self.horizontalLayoutWidget_11)
        self.PlayerMaleCombo10.setObjectName("PlayerMaleCombo10")
        self.horizontalLayout_13.addWidget(self.PlayerMaleCombo10)
        self.PlayerMaleCheck10 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_11)
        self.PlayerMaleCheck10.setObjectName("PlayerMaleCheck10")
        self.horizontalLayout_13.addWidget(self.PlayerMaleCheck10)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.groupBox_6)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.PlayerMaleCombo11 = QtWidgets.QComboBox(self.horizontalLayoutWidget_12)
        self.PlayerMaleCombo11.setObjectName("PlayerMaleCombo11")
        self.horizontalLayout_14.addWidget(self.PlayerMaleCombo11)
        self.PlayerMaleCheck11 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_12)
        self.PlayerMaleCheck11.setObjectName("PlayerMaleCheck11")
        self.horizontalLayout_14.addWidget(self.PlayerMaleCheck11)
        self.verticalLayout_4.addWidget(self.groupBox_6)
        self.groupBox_18 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_18.setObjectName("groupBox_18")
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self.groupBox_18)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.PlayerMaleCombo12 = QtWidgets.QComboBox(self.horizontalLayoutWidget_13)
        self.PlayerMaleCombo12.setObjectName("PlayerMaleCombo12")
        self.horizontalLayout_15.addWidget(self.PlayerMaleCombo12)
        self.PlayerMaleCheck12 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_13)
        self.PlayerMaleCheck12.setObjectName("PlayerMaleCheck12")
        self.horizontalLayout_15.addWidget(self.PlayerMaleCheck12)
        self.verticalLayout_4.addWidget(self.groupBox_18)
        self.groupBox_7 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayoutWidget_14 = QtWidgets.QWidget(self.groupBox_7)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.PlayerMaleCombo13 = QtWidgets.QComboBox(self.horizontalLayoutWidget_14)
        self.PlayerMaleCombo13.setObjectName("PlayerMaleCombo13")
        self.horizontalLayout_16.addWidget(self.PlayerMaleCombo13)
        self.PlayerMaleCheck13 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_14)
        self.PlayerMaleCheck13.setObjectName("PlayerMaleCheck13")
        self.horizontalLayout_16.addWidget(self.PlayerMaleCheck13)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayoutWidget_15 = QtWidgets.QWidget(self.groupBox_8)
        self.horizontalLayoutWidget_15.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_15.setObjectName("horizontalLayoutWidget_15")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_15)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.PlayerMaleCombo14 = QtWidgets.QComboBox(self.horizontalLayoutWidget_15)
        self.PlayerMaleCombo14.setObjectName("PlayerMaleCombo14")
        self.horizontalLayout_17.addWidget(self.PlayerMaleCombo14)
        self.PlayerMaleCheck14 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_15)
        self.PlayerMaleCheck14.setObjectName("PlayerMaleCheck14")
        self.horizontalLayout_17.addWidget(self.PlayerMaleCheck14)
        self.verticalLayout_4.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayoutWidget_16 = QtWidgets.QWidget(self.groupBox_9)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_16.setObjectName("horizontalLayoutWidget_16")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.PlayerMaleCombo15 = QtWidgets.QComboBox(self.horizontalLayoutWidget_16)
        self.PlayerMaleCombo15.setObjectName("PlayerMaleCombo15")
        self.horizontalLayout_18.addWidget(self.PlayerMaleCombo15)
        self.PlayerMaleCheck15 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_16)
        self.PlayerMaleCheck15.setObjectName("PlayerMaleCheck15")
        self.horizontalLayout_18.addWidget(self.PlayerMaleCheck15)
        self.verticalLayout_4.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayoutWidget_17 = QtWidgets.QWidget(self.groupBox_10)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_17.setObjectName("horizontalLayoutWidget_17")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.PlayerMaleCombo16 = QtWidgets.QComboBox(self.horizontalLayoutWidget_17)
        self.PlayerMaleCombo16.setObjectName("PlayerMaleCombo16")
        self.horizontalLayout_19.addWidget(self.PlayerMaleCombo16)
        self.PlayerMaleCheck16 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_17)
        self.PlayerMaleCheck16.setObjectName("PlayerMaleCheck16")
        self.horizontalLayout_19.addWidget(self.PlayerMaleCheck16)
        self.verticalLayout_4.addWidget(self.groupBox_10)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 19, 371, 731))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_19 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_19.setObjectName("groupBox_19")
        self.horizontalLayoutWidget_18 = QtWidgets.QWidget(self.groupBox_19)
        self.horizontalLayoutWidget_18.setGeometry(QtCore.QRect(49, 10, 311, 22))
        self.horizontalLayoutWidget_18.setObjectName("horizontalLayoutWidget_18")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_18)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.PlayerFemaleCombo1 = QtWidgets.QComboBox(self.horizontalLayoutWidget_18)
        self.PlayerFemaleCombo1.setObjectName("PlayerFemaleCombo1")
        self.horizontalLayout_20.addWidget(self.PlayerFemaleCombo1)
        self.PlayerFemaleCheck1 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_18)
        self.PlayerFemaleCheck1.setObjectName("PlayerFemaleCheck1")
        self.horizontalLayout_20.addWidget(self.PlayerFemaleCheck1)
        self.verticalLayout_5.addWidget(self.groupBox_19)
        self.groupBox_20 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_20.setObjectName("groupBox_20")
        self.horizontalLayoutWidget_19 = QtWidgets.QWidget(self.groupBox_20)
        self.horizontalLayoutWidget_19.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_19.setObjectName("horizontalLayoutWidget_19")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_19)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.PlayerFemaleCombo2 = QtWidgets.QComboBox(self.horizontalLayoutWidget_19)
        self.PlayerFemaleCombo2.setObjectName("PlayerFemaleCombo2")
        self.horizontalLayout_21.addWidget(self.PlayerFemaleCombo2)
        self.PlayerFemaleCheck2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_19)
        self.PlayerFemaleCheck2.setObjectName("PlayerFemaleCheck2")
        self.horizontalLayout_21.addWidget(self.PlayerFemaleCheck2)
        self.verticalLayout_5.addWidget(self.groupBox_20)
        self.groupBox_21 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_21.setObjectName("groupBox_21")
        self.horizontalLayoutWidget_20 = QtWidgets.QWidget(self.groupBox_21)
        self.horizontalLayoutWidget_20.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_20.setObjectName("horizontalLayoutWidget_20")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_20)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.PlayerFemaleCombo3 = QtWidgets.QComboBox(self.horizontalLayoutWidget_20)
        self.PlayerFemaleCombo3.setObjectName("PlayerFemaleCombo3")
        self.horizontalLayout_22.addWidget(self.PlayerFemaleCombo3)
        self.PlayerFemaleCheck3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_20)
        self.PlayerFemaleCheck3.setObjectName("PlayerFemaleCheck3")
        self.horizontalLayout_22.addWidget(self.PlayerFemaleCheck3)
        self.verticalLayout_5.addWidget(self.groupBox_21)
        self.groupBox_22 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_22.setObjectName("groupBox_22")
        self.horizontalLayoutWidget_21 = QtWidgets.QWidget(self.groupBox_22)
        self.horizontalLayoutWidget_21.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_21.setObjectName("horizontalLayoutWidget_21")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_21)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.PlayerFemaleCombo4 = QtWidgets.QComboBox(self.horizontalLayoutWidget_21)
        self.PlayerFemaleCombo4.setObjectName("PlayerFemaleCombo4")
        self.horizontalLayout_23.addWidget(self.PlayerFemaleCombo4)
        self.PlayerFemaleCheck4 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_21)
        self.PlayerFemaleCheck4.setObjectName("PlayerFemaleCheck4")
        self.horizontalLayout_23.addWidget(self.PlayerFemaleCheck4)
        self.verticalLayout_5.addWidget(self.groupBox_22)
        self.groupBox_23 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_23.setObjectName("groupBox_23")
        self.horizontalLayoutWidget_22 = QtWidgets.QWidget(self.groupBox_23)
        self.horizontalLayoutWidget_22.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_22.setObjectName("horizontalLayoutWidget_22")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_22)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.PlayerFemaleCombo5 = QtWidgets.QComboBox(self.horizontalLayoutWidget_22)
        self.PlayerFemaleCombo5.setObjectName("PlayerFemaleCombo5")
        self.horizontalLayout_24.addWidget(self.PlayerFemaleCombo5)
        self.PlayerFemaleCheck5 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_22)
        self.PlayerFemaleCheck5.setObjectName("PlayerFemaleCheck5")
        self.horizontalLayout_24.addWidget(self.PlayerFemaleCheck5)
        self.verticalLayout_5.addWidget(self.groupBox_23)
        self.groupBox_24 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_24.setObjectName("groupBox_24")
        self.horizontalLayoutWidget_23 = QtWidgets.QWidget(self.groupBox_24)
        self.horizontalLayoutWidget_23.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_23.setObjectName("horizontalLayoutWidget_23")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_23)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.PlayerFemaleCombo6 = QtWidgets.QComboBox(self.horizontalLayoutWidget_23)
        self.PlayerFemaleCombo6.setObjectName("PlayerFemaleCombo6")
        self.horizontalLayout_25.addWidget(self.PlayerFemaleCombo6)
        self.PlayerFemaleCheck6 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_23)
        self.PlayerFemaleCheck6.setObjectName("PlayerFemaleCheck6")
        self.horizontalLayout_25.addWidget(self.PlayerFemaleCheck6)
        self.verticalLayout_5.addWidget(self.groupBox_24)
        self.groupBox_25 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_25.setObjectName("groupBox_25")
        self.horizontalLayoutWidget_24 = QtWidgets.QWidget(self.groupBox_25)
        self.horizontalLayoutWidget_24.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_24.setObjectName("horizontalLayoutWidget_24")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_24)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.PlayerFemaleCombo7 = QtWidgets.QComboBox(self.horizontalLayoutWidget_24)
        self.PlayerFemaleCombo7.setObjectName("PlayerFemaleCombo7")
        self.horizontalLayout_26.addWidget(self.PlayerFemaleCombo7)
        self.PlayerFemaleCheck7 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_24)
        self.PlayerFemaleCheck7.setObjectName("PlayerFemaleCheck7")
        self.horizontalLayout_26.addWidget(self.PlayerFemaleCheck7)
        self.verticalLayout_5.addWidget(self.groupBox_25)
        self.groupBox_26 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_26.setObjectName("groupBox_26")
        self.horizontalLayoutWidget_25 = QtWidgets.QWidget(self.groupBox_26)
        self.horizontalLayoutWidget_25.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_25.setObjectName("horizontalLayoutWidget_25")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_25)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.PlayerFemaleCombo8 = QtWidgets.QComboBox(self.horizontalLayoutWidget_25)
        self.PlayerFemaleCombo8.setObjectName("PlayerFemaleCombo8")
        self.horizontalLayout_27.addWidget(self.PlayerFemaleCombo8)
        self.PlayerFemaleCheck8 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_25)
        self.PlayerFemaleCheck8.setObjectName("PlayerFemaleCheck8")
        self.horizontalLayout_27.addWidget(self.PlayerFemaleCheck8)
        self.verticalLayout_5.addWidget(self.groupBox_26)
        self.groupBox_27 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_27.setObjectName("groupBox_27")
        self.horizontalLayoutWidget_26 = QtWidgets.QWidget(self.groupBox_27)
        self.horizontalLayoutWidget_26.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_26.setObjectName("horizontalLayoutWidget_26")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_26)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.PlayerFemaleCombo9 = QtWidgets.QComboBox(self.horizontalLayoutWidget_26)
        self.PlayerFemaleCombo9.setObjectName("PlayerFemaleCombo9")
        self.horizontalLayout_28.addWidget(self.PlayerFemaleCombo9)
        self.PlayerFemaleCheck9 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_26)
        self.PlayerFemaleCheck9.setObjectName("PlayerFemaleCheck9")
        self.horizontalLayout_28.addWidget(self.PlayerFemaleCheck9)
        self.verticalLayout_5.addWidget(self.groupBox_27)
        self.groupBox_28 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_28.setObjectName("groupBox_28")
        self.horizontalLayoutWidget_27 = QtWidgets.QWidget(self.groupBox_28)
        self.horizontalLayoutWidget_27.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_27.setObjectName("horizontalLayoutWidget_27")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_27)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.PlayerFemaleCombo10 = QtWidgets.QComboBox(self.horizontalLayoutWidget_27)
        self.PlayerFemaleCombo10.setObjectName("PlayerFemaleCombo10")
        self.horizontalLayout_29.addWidget(self.PlayerFemaleCombo10)
        self.PlayerFemaleCheck10 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_27)
        self.PlayerFemaleCheck10.setObjectName("PlayerFemaleCheck10")
        self.horizontalLayout_29.addWidget(self.PlayerFemaleCheck10)
        self.verticalLayout_5.addWidget(self.groupBox_28)
        self.groupBox_29 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_29.setObjectName("groupBox_29")
        self.horizontalLayoutWidget_28 = QtWidgets.QWidget(self.groupBox_29)
        self.horizontalLayoutWidget_28.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_28.setObjectName("horizontalLayoutWidget_28")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_28)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.PlayerFemaleCombo11 = QtWidgets.QComboBox(self.horizontalLayoutWidget_28)
        self.PlayerFemaleCombo11.setObjectName("PlayerFemaleCombo11")
        self.horizontalLayout_30.addWidget(self.PlayerFemaleCombo11)
        self.PlayerFemaleCheck11 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_28)
        self.PlayerFemaleCheck11.setObjectName("PlayerFemaleCheck11")
        self.horizontalLayout_30.addWidget(self.PlayerFemaleCheck11)
        self.verticalLayout_5.addWidget(self.groupBox_29)
        self.groupBox_30 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_30.setObjectName("groupBox_30")
        self.horizontalLayoutWidget_29 = QtWidgets.QWidget(self.groupBox_30)
        self.horizontalLayoutWidget_29.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_29.setObjectName("horizontalLayoutWidget_29")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_29)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.PlayerFemaleCombo12 = QtWidgets.QComboBox(self.horizontalLayoutWidget_29)
        self.PlayerFemaleCombo12.setObjectName("PlayerFemaleCombo12")
        self.horizontalLayout_31.addWidget(self.PlayerFemaleCombo12)
        self.PlayerFemaleCheck12 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_29)
        self.PlayerFemaleCheck12.setObjectName("PlayerFemaleCheck12")
        self.horizontalLayout_31.addWidget(self.PlayerFemaleCheck12)
        self.verticalLayout_5.addWidget(self.groupBox_30)
        self.groupBox_31 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_31.setObjectName("groupBox_31")
        self.horizontalLayoutWidget_30 = QtWidgets.QWidget(self.groupBox_31)
        self.horizontalLayoutWidget_30.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_30.setObjectName("horizontalLayoutWidget_30")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_30)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.PlayerFemaleCombo13 = QtWidgets.QComboBox(self.horizontalLayoutWidget_30)
        self.PlayerFemaleCombo13.setObjectName("PlayerFemaleCombo13")
        self.horizontalLayout_32.addWidget(self.PlayerFemaleCombo13)
        self.PlayerFemaleCheck13 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_30)
        self.PlayerFemaleCheck13.setObjectName("PlayerFemaleCheck13")
        self.horizontalLayout_32.addWidget(self.PlayerFemaleCheck13)
        self.verticalLayout_5.addWidget(self.groupBox_31)
        self.groupBox_32 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_32.setObjectName("groupBox_32")
        self.horizontalLayoutWidget_31 = QtWidgets.QWidget(self.groupBox_32)
        self.horizontalLayoutWidget_31.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_31.setObjectName("horizontalLayoutWidget_31")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_31)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.PlayerFemaleCombo14 = QtWidgets.QComboBox(self.horizontalLayoutWidget_31)
        self.PlayerFemaleCombo14.setObjectName("PlayerFemaleCombo14")
        self.horizontalLayout_33.addWidget(self.PlayerFemaleCombo14)
        self.PlayerFemaleCheck14 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_31)
        self.PlayerFemaleCheck14.setObjectName("PlayerFemaleCheck14")
        self.horizontalLayout_33.addWidget(self.PlayerFemaleCheck14)
        self.verticalLayout_5.addWidget(self.groupBox_32)
        self.groupBox_33 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_33.setObjectName("groupBox_33")
        self.horizontalLayoutWidget_32 = QtWidgets.QWidget(self.groupBox_33)
        self.horizontalLayoutWidget_32.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_32.setObjectName("horizontalLayoutWidget_32")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_32)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.PlayerFemaleCombo15 = QtWidgets.QComboBox(self.horizontalLayoutWidget_32)
        self.PlayerFemaleCombo15.setObjectName("PlayerFemaleCombo15")
        self.horizontalLayout_34.addWidget(self.PlayerFemaleCombo15)
        self.PlayerFemaleCheck15 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_32)
        self.PlayerFemaleCheck15.setObjectName("PlayerFemaleCheck15")
        self.horizontalLayout_34.addWidget(self.PlayerFemaleCheck15)
        self.verticalLayout_5.addWidget(self.groupBox_33)
        self.groupBox_34 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_34.setObjectName("groupBox_34")
        self.horizontalLayoutWidget_33 = QtWidgets.QWidget(self.groupBox_34)
        self.horizontalLayoutWidget_33.setGeometry(QtCore.QRect(50, 10, 311, 22))
        self.horizontalLayoutWidget_33.setObjectName("horizontalLayoutWidget_33")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_33)
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.PlayerFemaleCombo16 = QtWidgets.QComboBox(self.horizontalLayoutWidget_33)
        self.PlayerFemaleCombo16.setObjectName("PlayerFemaleCombo16")
        self.horizontalLayout_35.addWidget(self.PlayerFemaleCombo16)
        self.PlayerFemaleCheck16 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_33)
        self.PlayerFemaleCheck16.setObjectName("PlayerFemaleCheck16")
        self.horizontalLayout_35.addWidget(self.PlayerFemaleCheck16)
        self.verticalLayout_5.addWidget(self.groupBox_34)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 10, 701, 751))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.PartnerCombo4 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo4.setObjectName("PartnerCombo4")
        self.gridLayout.addWidget(self.PartnerCombo4, 3, 0, 1, 1)
        self.PartnerCombo7 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo7.setObjectName("PartnerCombo7")
        self.gridLayout.addWidget(self.PartnerCombo7, 6, 0, 1, 1)
        self.PartnerCombo2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo2.setObjectName("PartnerCombo2")
        self.gridLayout.addWidget(self.PartnerCombo2, 1, 0, 1, 1)
        self.PartnerCombo3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo3.setObjectName("PartnerCombo3")
        self.gridLayout.addWidget(self.PartnerCombo3, 2, 0, 1, 1)
        self.PartnerCombo5 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo5.setObjectName("PartnerCombo5")
        self.gridLayout.addWidget(self.PartnerCombo5, 4, 0, 1, 1)
        self.PartnerCombo8 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo8.setObjectName("PartnerCombo8")
        self.gridLayout.addWidget(self.PartnerCombo8, 7, 0, 1, 1)
        self.PartnerCombo1 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo1.setObjectName("PartnerCombo1")
        self.gridLayout.addWidget(self.PartnerCombo1, 0, 0, 1, 1)
        self.PartnerCombo9 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo9.setObjectName("PartnerCombo9")
        self.gridLayout.addWidget(self.PartnerCombo9, 8, 0, 1, 1)
        self.PartnerCheck1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck1.setObjectName("PartnerCheck1")
        self.gridLayout.addWidget(self.PartnerCheck1, 0, 1, 1, 1)
        self.PartnerCheck12 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck12.setObjectName("PartnerCheck12")
        self.gridLayout.addWidget(self.PartnerCheck12, 0, 3, 1, 1)
        self.PartnerCombo12 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo12.setObjectName("PartnerCombo12")
        self.gridLayout.addWidget(self.PartnerCombo12, 0, 2, 1, 1)
        self.PartnerCombo6 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo6.setObjectName("PartnerCombo6")
        self.gridLayout.addWidget(self.PartnerCombo6, 5, 0, 1, 1)
        self.PartnerCombo10 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo10.setObjectName("PartnerCombo10")
        self.gridLayout.addWidget(self.PartnerCombo10, 9, 0, 1, 1)
        self.PartnerCombo11 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo11.setObjectName("PartnerCombo11")
        self.gridLayout.addWidget(self.PartnerCombo11, 10, 0, 1, 1)
        self.PartnerCombo13 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo13.setObjectName("PartnerCombo13")
        self.gridLayout.addWidget(self.PartnerCombo13, 1, 2, 1, 1)
        self.PartnerCombo14 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo14.setObjectName("PartnerCombo14")
        self.gridLayout.addWidget(self.PartnerCombo14, 2, 2, 1, 1)
        self.PartnerCombo15 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo15.setObjectName("PartnerCombo15")
        self.gridLayout.addWidget(self.PartnerCombo15, 3, 2, 1, 1)
        self.PartnerCombo16 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo16.setObjectName("PartnerCombo16")
        self.gridLayout.addWidget(self.PartnerCombo16, 4, 2, 1, 1)
        self.PartnerCombo17 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo17.setObjectName("PartnerCombo17")
        self.gridLayout.addWidget(self.PartnerCombo17, 5, 2, 1, 1)
        self.PartnerCombo18 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo18.setObjectName("PartnerCombo18")
        self.gridLayout.addWidget(self.PartnerCombo18, 6, 2, 1, 1)
        self.PartnerCombo19 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo19.setObjectName("PartnerCombo19")
        self.gridLayout.addWidget(self.PartnerCombo19, 7, 2, 1, 1)
        self.PartnerCombo20 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo20.setObjectName("PartnerCombo20")
        self.gridLayout.addWidget(self.PartnerCombo20, 8, 2, 1, 1)
        self.PartnerCombo21 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.PartnerCombo21.setObjectName("PartnerCombo21")
        self.gridLayout.addWidget(self.PartnerCombo21, 9, 2, 1, 1)
        self.PartnerCheck2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck2.setObjectName("PartnerCheck2")
        self.gridLayout.addWidget(self.PartnerCheck2, 1, 1, 1, 1)
        self.PartnerCheck3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck3.setObjectName("PartnerCheck3")
        self.gridLayout.addWidget(self.PartnerCheck3, 2, 1, 1, 1)
        self.PartnerCheck4 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck4.setObjectName("PartnerCheck4")
        self.gridLayout.addWidget(self.PartnerCheck4, 3, 1, 1, 1)
        self.PartnerCheck5 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck5.setObjectName("PartnerCheck5")
        self.gridLayout.addWidget(self.PartnerCheck5, 4, 1, 1, 1)
        self.PartnerCheck6 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck6.setObjectName("PartnerCheck6")
        self.gridLayout.addWidget(self.PartnerCheck6, 5, 1, 1, 1)
        self.PartnerCheck7 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck7.setObjectName("PartnerCheck7")
        self.gridLayout.addWidget(self.PartnerCheck7, 6, 1, 1, 1)
        self.PartnerCheck8 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck8.setObjectName("PartnerCheck8")
        self.gridLayout.addWidget(self.PartnerCheck8, 7, 1, 1, 1)
        self.PartnerCheck9 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck9.setObjectName("PartnerCheck9")
        self.gridLayout.addWidget(self.PartnerCheck9, 8, 1, 1, 1)
        self.PartnerCheck10 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck10.setObjectName("PartnerCheck10")
        self.gridLayout.addWidget(self.PartnerCheck10, 9, 1, 1, 1)
        self.PartnerCheck11 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck11.setObjectName("PartnerCheck11")
        self.gridLayout.addWidget(self.PartnerCheck11, 10, 1, 1, 1)
        self.PartnerCheck13 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck13.setObjectName("PartnerCheck13")
        self.gridLayout.addWidget(self.PartnerCheck13, 1, 3, 1, 1)
        self.PartnerCheck14 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck14.setObjectName("PartnerCheck14")
        self.gridLayout.addWidget(self.PartnerCheck14, 2, 3, 1, 1)
        self.PartnerCheck15 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck15.setObjectName("PartnerCheck15")
        self.gridLayout.addWidget(self.PartnerCheck15, 3, 3, 1, 1)
        self.PartnerCheck16 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck16.setObjectName("PartnerCheck16")
        self.gridLayout.addWidget(self.PartnerCheck16, 4, 3, 1, 1)
        self.PartnerCheck17 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck17.setObjectName("PartnerCheck17")
        self.gridLayout.addWidget(self.PartnerCheck17, 5, 3, 1, 1)
        self.PartnerCheck18 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck18.setObjectName("PartnerCheck18")
        self.gridLayout.addWidget(self.PartnerCheck18, 6, 3, 1, 1)
        self.PartnerCheck19 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck19.setObjectName("PartnerCheck19")
        self.gridLayout.addWidget(self.PartnerCheck19, 7, 3, 1, 1)
        self.PartnerCheck20 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck20.setObjectName("PartnerCheck20")
        self.gridLayout.addWidget(self.PartnerCheck20, 8, 3, 1, 1)
        self.PartnerCheck21 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.PartnerCheck21.setObjectName("PartnerCheck21")
        self.gridLayout.addWidget(self.PartnerCheck21, 9, 3, 1, 1)
        self.tabWidget.addTab(self.tab2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        self.openButton.setObjectName("openButton")
        self.horizontalLayout.addWidget(self.openButton)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName("actionSave")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PMD Sky Starter Editor"))
        self.groupBox.setTitle(_translate("MainWindow", "Male"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Hardy"))
        self.PlayerMaleCheck1.setText(_translate("MainWindow", "Female"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Docile"))
        self.PlayerMaleCheck2.setText(_translate("MainWindow", "Female"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Brave"))
        self.PlayerMaleCheck3.setText(_translate("MainWindow", "Female"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Jolly"))
        self.PlayerMaleCheck4.setText(_translate("MainWindow", "Female"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Impish"))
        self.PlayerMaleCheck5.setText(_translate("MainWindow", "Female"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Naive"))
        self.PlayerMaleCheck6.setText(_translate("MainWindow", "Female"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Timid"))
        self.PlayerMaleCheck7.setText(_translate("MainWindow", "Female"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Hasty"))
        self.PlayerMaleCheck8.setText(_translate("MainWindow", "Female"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Sassy"))
        self.PlayerMaleCheck9.setText(_translate("MainWindow", "Female"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Calm"))
        self.PlayerMaleCheck10.setText(_translate("MainWindow", "Female"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Relaxed"))
        self.PlayerMaleCheck11.setText(_translate("MainWindow", "Female"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Lonely"))
        self.PlayerMaleCheck12.setText(_translate("MainWindow", "Female"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Quirky"))
        self.PlayerMaleCheck13.setText(_translate("MainWindow", "Female"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Quiet"))
        self.PlayerMaleCheck14.setText(_translate("MainWindow", "Female"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Rash"))
        self.PlayerMaleCheck15.setText(_translate("MainWindow", "Female"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Bold"))
        self.PlayerMaleCheck16.setText(_translate("MainWindow", "Female"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Female"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Hardy"))
        self.PlayerFemaleCheck1.setText(_translate("MainWindow", "Female"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Docile"))
        self.PlayerFemaleCheck2.setText(_translate("MainWindow", "Female"))
        self.groupBox_21.setTitle(_translate("MainWindow", "Brave"))
        self.PlayerFemaleCheck3.setText(_translate("MainWindow", "Female"))
        self.groupBox_22.setTitle(_translate("MainWindow", "Jolly"))
        self.PlayerFemaleCheck4.setText(_translate("MainWindow", "Female"))
        self.groupBox_23.setTitle(_translate("MainWindow", "Impish"))
        self.PlayerFemaleCheck5.setText(_translate("MainWindow", "Female"))
        self.groupBox_24.setTitle(_translate("MainWindow", "Naive"))
        self.PlayerFemaleCheck6.setText(_translate("MainWindow", "Female"))
        self.groupBox_25.setTitle(_translate("MainWindow", "Timid"))
        self.PlayerFemaleCheck7.setText(_translate("MainWindow", "Female"))
        self.groupBox_26.setTitle(_translate("MainWindow", "Hasty"))
        self.PlayerFemaleCheck8.setText(_translate("MainWindow", "Female"))
        self.groupBox_27.setTitle(_translate("MainWindow", "Sassy"))
        self.PlayerFemaleCheck9.setText(_translate("MainWindow", "Female"))
        self.groupBox_28.setTitle(_translate("MainWindow", "Calm"))
        self.PlayerFemaleCheck10.setText(_translate("MainWindow", "Female"))
        self.groupBox_29.setTitle(_translate("MainWindow", "Relaxed"))
        self.PlayerFemaleCheck11.setText(_translate("MainWindow", "Female"))
        self.groupBox_30.setTitle(_translate("MainWindow", "Lonely"))
        self.PlayerFemaleCheck12.setText(_translate("MainWindow", "Female"))
        self.groupBox_31.setTitle(_translate("MainWindow", "Quirky"))
        self.PlayerFemaleCheck13.setText(_translate("MainWindow", "Female"))
        self.groupBox_32.setTitle(_translate("MainWindow", "Quiet"))
        self.PlayerFemaleCheck14.setText(_translate("MainWindow", "Female"))
        self.groupBox_33.setTitle(_translate("MainWindow", "Rash"))
        self.PlayerFemaleCheck15.setText(_translate("MainWindow", "Female"))
        self.groupBox_34.setTitle(_translate("MainWindow", "Bold"))
        self.PlayerFemaleCheck16.setText(_translate("MainWindow", "Female"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Player"))
        self.PartnerCheck1.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck12.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck2.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck3.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck4.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck5.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck6.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck7.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck8.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck9.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck10.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck11.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck13.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck14.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck15.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck16.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck17.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck18.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck19.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck20.setText(_translate("MainWindow", "Female"))
        self.PartnerCheck21.setText(_translate("MainWindow", "Female"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Partner"))
        self.openButton.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
